# Generated by Django 4.0.5 on 2022-07-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_drink_size_alter_categories_name_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allergy',
            table='allergy',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='size',
            table='sizes',
        ),
    ]
