# Generated by Django 4.0.5 on 2022-07-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='saturated_gat_g',
            new_name='saturated_fat_g',
        ),
    ]
