# Generated by Django 4.0.5 on 2022-07-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_saturated_gat_g_nutrition_saturated_fat_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='size_fluid_ounce',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='size_ml',
        ),
    ]
